version: "2"

run:
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - errcheck
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - gocritic
    #- shadow
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocyclo
    - revive
    - goconst
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        #- security
      disabled-checks:
        - commentedOutCode
        - ifElseChain
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - pkg/aws
