name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Set up linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Test
      run: make test

    - name: Test with coverage
      run: make test-coverage

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Clean before build
      run: make clean

    - name: Build
      run: make build 